head.load(
"generators/Blockly/logic.js",
"generators/Blockly/math.js",
"generators/Blockly/text.js",
function() {
    // Call a function when done
    console.log("Done loading Blockly Generators");
});

head.load(
"generators/BlocklyArduino/array.js",
"generators/BlocklyArduino/loops.js",
"generators/BlocklyArduino/math.js",
"generators/BlocklyArduino/procedures.js",
"generators/BlocklyArduino/variables.js",
function() {
    // Call a function when done
    console.log("Done loading BlocklyArduino Generators");
});

head.load(
"generators/arduino/anemometer.js",
"generators/arduino/arduino_base.js",
"generators/arduino/arduino_BT.js",
"generators/arduino/arduino_io.js",
"generators/arduino/arduino_conversion.js",
"generators/arduino/arduino_serial.js",
"generators/arduino/arduino_softserial.js",
"generators/arduino/Adafruit_motorshield_v1.js",
"generators/arduino/Adafruit_motorshield_v2.js",
"generators/arduino/Adafruit_RGB_LCD_Shield.js",
"generators/arduino/ADXL362_gyroscope.js",
"generators/arduino/APDS-9960_RGB_Gesture.js",
"generators/arduino/arduino_shield.js",
"generators/arduino/autoduino.js",
"generators/arduino/bitbloq.js",
"generators/arduino/Bluetooth_Electronics.js",
"generators/arduino/blynk_cc.js",
"generators/arduino/capacitiveSensor.js",
"generators/arduino/keypad.js",
"generators/arduino/dfrobot_dfplayer-mini-mp3.js",
"generators/arduino/dfrobot_IIC_to_GPIO_Shield_V2.js",
"generators/arduino/dfrobot_ISD1820.js",
"generators/arduino/dfrobot_romeo_v2_1.js",
"generators/arduino/dfrobot_romeo_v2_2.js",
"generators/arduino/dfrobot_romeo_v2_3.js",
"generators/arduino/dfrobot_romeo_ble_3.js",
"generators/arduino/display-oled-128x64-i2c.js",
"generators/arduino/drone.js",
"generators/arduino/ds18b20.js",
"generators/arduino/esp8266.js",
"generators/arduino/EsusBoard.js",
"generators/arduino/ethernet.js",
"generators/arduino/fischertechnik.js",
"generators/arduino/flycamone-eco-v2.js",
"generators/arduino/grove.js",
"generators/arduino/grove_beginner_kit.js",
"generators/arduino/grove_TF_Mini_LiDAR.js",
"generators/arduino/grove_VL53L0X.js",
"generators/arduino/html.js",
"generators/arduino/HX711.js",
"generators/arduino/I2C.js",
"generators/arduino/I2C_to_GPIO_Module.js",
"generators/arduino/icn.js",
"generators/arduino/IR.js",
"generators/arduino/jfblocks.js",
"generators/arduino/jeulin_maquette_feux.js",
"generators/arduino/lcd_i2c.js",
"generators/arduino/led-rgb-ws2812b.js",
"generators/arduino/matrix-led-rgb-ws2812.js",
"generators/arduino/mbot_niv1.js",
"generators/arduino/mbot_niv2.js",
"generators/arduino/mbot_niv3.js",
"generators/arduino/mbot_niv4.js",
//20191010
"generators/arduino/micromachine.js",
"generators/arduino/microsaurus.js",
//20191010
"generators/arduino/MRduino.js",
"generators/arduino/MRduino2.js",
"generators/arduino/multi-function.js",
"generators/arduino/myhumankit.js",
"generators/arduino/nrf24l01.js",
"generators/arduino/null.js",
"generators/arduino/otto.js",
"generators/arduino/peguino_actuators.js",
"generators/arduino/peguino_sensors.js",
"generators/arduino/petitbot.js",
"generators/arduino/pulseSensor.js",
"generators/arduino/QTR-1RC.js",
"generators/arduino/RF433.js",
"generators/arduino/RFID.js",
"generators/arduino/robobox_IRremote.js",
"generators/arduino/robobox_month4.js",
"generators/arduino/robobox_month6.js",
"generators/arduino/robobox_month8.js",
"generators/arduino/robobox_sensors.js",
"generators/arduino/robobox_servo.js",
"generators/arduino/robot_motors.js",
"generators/arduino/robot_misc.js",
"generators/arduino/robuno.js",
"generators/arduino/seeed_music_shield_2.2.js",
"generators/arduino/sensor_actuator.js",
"generators/arduino/servo.js",
"generators/arduino/Sharp_IR.js",
"generators/arduino/SPI.js",
"generators/arduino/stendhal.js",
"generators/arduino/stepper_motor.js",
"generators/arduino/storage.js",
"generators/arduino/technozone51.js",
"generators/arduino/tsl2561.js",
"generators/arduino/unipolar_stepper_motor.js",
"generators/arduino/virtuino.js",
"generators/arduino/wiichuck.js",
"generators/arduino/zumo_auto.js",
"generators/arduino/zumo_motors.js",
"generators/arduino/zumo_sensors.js",
"generators/arduino/RTC_DS3231.js",
"generators/arduino/Adafruit_SSD1306.js",
"generators/arduino/LoRa.js",

function() {
    // Call a function when done
    console.log("Done loading Various Arduino Generators");
});
