#define CMD_PIN 0x10
#define CMD_PIN_MODE_INPUT 0x10
#define CMD_PIN_MODE_OUTPUT 0x11
#define CMD_DIGITAL_WRITE_LO 0x12
#define CMD_DIGITAL_WRITE_HI 0x13
#define CMD_ANALOG_WRITE 0x14
#define CMD_DIGITAL_READ 0x15
#define CMD_ANALOG_READ 0x16

#define CMD_MEMORY 0x20
#define CMD_EEPROM_WRITE 0x20
#define CMD_EEPROM_READ 0x21

//#define CMD_TONE_WRITE 0x29

#define CMD_SERVO_ATTACH 0x30
#define CMD_SERVO_DETACH 0x40
#define CMD_SERVO_WRITE 0x50
#define CMD_SERVO_READ 0x60

#define CMD_BUS 0x70
#define CMD_WIRE_BEGIN 0x72
#define CMD_WIRE_REQUEST_FROM 0x73
#define CMD_WIRE_BEGIN_XFER 0x74
#define CMD_WIRE_END_XFER 0x75
#define CMD_WIRE_READ 0x76
#define CMD_WIRE_WRITE 0x77
#define CMD_WIRE_AVAILABLE 0x78

#define CMD_DISPLAY 0xD0
#define CMD_RAINBOW_PIXEL 0xD1
#define CMD_RAINBOW_CLS 0xD2
#define CMD_RAINBOW_DRAW 0xD3
